config/routes.rb
Rails.application.routes.draw do

  get '/install-instructions', to: 'steps#install_instructions'
  get '/getting-started', to: 'steps#getting_started'
  get '/add-project-to-git', to: 'steps#add_project_to_git'
  get '/running-application', to: 'steps#running_application'
  get '/creating-projects', to: 'steps#creating_projects'
  get '/validate-project-titles', to: 'steps#validate_project_titles'
  get '/authentication-with-devise', to: 'steps#authentication_with_devise'
  get '/setup-users', to: 'steps#setup_users'
  get '/add-authentication-forms-and-links', to: 'steps#add_authentication_forms_and_links'
  get '/create-comments', to: 'steps#create_comments'
  get '/display-comments', to: 'steps#display_comments'
  get '/submit-comments', to: 'steps#submit_comments'
  get '/add-projects-workflow', to: 'steps#add_projects_workflow'
  get '/next-steps', to: 'steps#next_steps'

  root to: 'steps#overview'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Rails Intermediate</a>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-sidebar">
  <li class="<%= 'active' if current_page?('/') %>">
    <%= link_to 'Overview', root_path %>
  </li>
  <li class="<%= 'active' if current_page?('/getting-started') %>">
    <%= link_to 'Getting Started', getting_started_path %>
  </li>
  <li class="<%= 'active' if current_page?('/add-project-to-git') %>">
    <%= link_to 'Add The Project To A Git Repo', add_project_to_git_path %>
  </li>
  <li class="<%= 'active' if current_page?('/running-application') %>">
    <%= link_to 'Running Your Application Locally', running_application_path %>
  </li>
  <li class="<%= 'active' if current_page?('/creating-projects') %>">
    <%= link_to 'Create Projects', creating_projects_path %>
  </li>
  <li class="<%= 'active' if current_page?('/validate-project-titles') %>">
    <%= link_to 'Validate Project Titles', validate_project_titles_path %>
  </li>
  <li class="<%= 'active' if current_page?('/authentication-with-devise') %>">
    <%= link_to 'Authentication with Devise', authentication_with_devise_path %>
  </li>
  <li class="<%= 'active' if current_page?('/setup-users') %>">
    <%= link_to 'Setup Users with Devise', setup_users_path %>
  </li>
  <li class="<%= 'active' if current_page?('/add-authentication-forms-and-links') %>">
    <%= link_to 'Add Authentication Forms and Links', add_authentication_forms_and_links_path %>
  </li>
  <li class="<%= 'active' if current_page?('/create-comments') %>">
    <%= link_to 'Create Comments', create_comments_path %>
  </li>
  <li class="<%= 'active' if current_page?('/display-comments') %>">
    <%= link_to 'Display Comments', display_comments_path %>
  </li>
  <li class="<%= 'active' if current_page?('/submit-comments') %>">
    <%= link_to 'Submit Comments', submit_comments_path %>
  </li>
  <li class="<%= 'active' if current_page?('/add-projects-workflow') %>">
    <%= link_to 'Add Workflow to your Projects', add_projects_workflow_path %>
  </li>
  <li class="<%= 'active' if current_page?('/next-steps') %>">
    <%= link_to 'Next Steps', next_steps_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Intermediate</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="http://bootswatch.com/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="http://yandex.st/highlightjs/8.0/styles/monokai.min.css">
  <script src="http://yandex.st/highlightjs/8.0/highlight.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <%= render 'layouts/navigation' %>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/steps/add_authentication_forms_and_links.html.erb
<h1 class="page-header">Adding login forms and links to our views</h1>
<blockquote>
  <p>
    Everything is ready for Milo to handle authentication. Let's add the necessary forms and links for our users to authenticate.
  </p>
</blockquote>
<h2>Goals</h2>
<ul>
  <li><h4>Create a demo user</h4></li>
  <li><h4>Block access to everyone, everywhere</h4></li>
  <li><h4>Add a link to log out the system</h4></li>
</ul>

<h3>Step 1</h3>
<blockquote>
  <p>Populate your database by adding this line of code to <code>db/seeds.rb</code></p>
  <pre><code>User.where(email: 'admin@demo.com').first_or_create(password: 'foobar11', password_confirmation: 'foobar11')</code></pre>
  <p>Run <code>rake db:seed</code> and visit <a href="http://localhost:3000">http://localhost:3000</a> when you're done.</p>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Everything is secret. Block access to everyone at the root.</p>
  <p>Add the following line to your <code>ApplicationController</code></p>
  <pre><code>before_action :authenticate_user!</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Add a <em>sign out</em> link to the top of your views. Copy the following in your <code>app/views/layouts/application.html.erb</code> file above <code>yield</code></p>
  <pre><code>&lt;body&gt;
  &lt;%= link_to 'Log out', destroy_user_session_path, method: :delete if user_signed_in? %&gt;
  &lt;%= yield %&gt;
&lt;/body&gt;</code></pre>
</blockquote>

<h2>Explanation</h2>
<blockquote>
  <p>
    Behind the scenes, our application inspects our (and our engines') view folders to find the required forms. The login and registration forms live in <code>Devise</code> folder structure but could be overriden by our application. <code>Devise</code> provide an easy generator to copy its view files to our application: <code class="ruby">rails g devise:views</code>.
  </p>
</blockquote>

app/views/steps/add_project_to_git.html.erb
<h1 class="page-header">Add The Project To A Git Repo</h1>
<h2>Goals</h2>
<ul>
  <li>
    <div class="message">
      <p>Create a local git repository</p>
    </div>
  </li>
  <li>
    <div class="message">
      <p>Add all our files to the git repository</p>
    </div>
  </li>
  <div class="message">
    <p>In order to publish our application, we need to add our application and any changes we make over time to a "revision control system". In our case we're going to use <em>git</em> because it is (relatively) easy and it is what our app server, <em>Heroku</em>, uses.</p>
  </div>
</ul>
<h3>Step 1</h3>
<blockquote>
  <div class="console">
    <span>Type this in the terminal:</span><code>git init</code>
  </div>
  <div class="message">
    <p>It doesn't look like anything really happened, but 'git init' initialized its repository (repo) in a hidden directory called <code>.git</code>. You can see this by typing <code>ls -a</code> (list all files).</p>
  </div>
</blockquote>
<h3>Step 2</h3>
<blockquote>
  <div class="console">
    <span>Type this in the terminal:</span><code>git status</code>
  </div>
  <div class="message">
    <p><code>git status</code> tells you everything git sees as modified, new, or missing.</p>
  </div>
  <div class="message">
    <p>The first time you run this, you should see a ton of stuff.</p>
  </div>
  <div class="message">
    <p>The second time you run this, you shouldn't see much of anything.</p>
  </div>
</blockquote>
<h3>Step 3</h3>
<blockquote>
  <div class="console">
    <span>Type this in the terminal:</span><code>git add .</code>
  </div>
  <div class="message">
    <p><code>git add .</code> tells git that you want to add the current directory (aka <code>.</code>) and everything under it to the repo.</p>
  </div>
</blockquote>
<div class="step">
  <h3>Step 4</h3>
  <blockquote>
    <div class="console">
      <span>Type this in the terminal:</span><code>git commit -m "Initial commit"</code>
    </div>
    <div class="message">
      <p><code>git commit</code> tells git to actually <em>do</em> all things you've said you wanted to do.</p>
    </div>
    <div class="message">
      <p>This is done in two steps so you can group multiple changes together.</p>
    </div>
    <div class="message">
      <p><code>-m "Initial commit"</code>  is just a shortcut to say what your commit message is. You can skip that part and git will bring up an editor to fill out a more detailed message.</p>
    </div>
  </blockquote>
</div>
<div class="explanation">
  <h2>Explanation</h2>
  <blockquote>
    <div class="message">
      <p>By checking your application into git now, you're creating a record of your starting point. Whenever you make a change during today's workshop, we'll add it to git before moving on. This way, if anything ever breaks, or you make a change you don't like, you can use git as an all-powerful "undo" technique. But that only works when you remember to commit early and often!</p>
    </div>
  </blockquote>
</div>

app/views/steps/add_projects_workflow.html.erb
<h1 class="page-header">Add Project Workflow</h1>
<blockquote>
  <p>
    Every project has a progress state. It is either <code>pending</code>, <code>ongoing</code>, <code>completed</code> or <code>canceled</code>. Add a state machine to your projects to keep track of their progress.
  </p>
</blockquote>
<h2>Goals</h2>
<blockquote>
  <ul>
    <li><h4>Use Rails 4.1 latest feature: <code>enum</code></h4></li>
    <li><h4>Generate a migration to add project's status</h4></li>
    <li><h4>Add status to projects index</h4></li>
  </ul>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>
    Generate the migration to store a project status.
  </p>
  <pre><code>rails g migration AddStatusToProjects status:integer</code></pre>
  <p>
    Before migration, set <code>default: 0</code> in your migration so that new projects have a default status <code>pending</code>.
  </p>
  <pre><code>rake db:migrate</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Use <code>enum</code> to add poor man's state machine to <code>Project</code></p>
  <pre><code class="ruby">class Project &lt; ActiveRecord::Base
  has_many :comments, as: :commentable
  validates :title, presence: true

  enum status: [:pending, :ongoing, :completed, :canceled]
end</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Display project's status on index and show views.</p>
  <p>This task is left for you to practice or complete in class with the group.</p>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p>Enable status editing from project form.</p>
  <p>First, add status input on project's form</p>
  <pre><code>&lt;div class="field"&gt;
  &lt;%= f.label :status %&gt;&lt;br&gt;
  &lt;%= f.select :status, Project.statuses.keys %&gt;
&lt;/div&gt;</code></pre>
  <p>Then, add <code>status</code> to the list of permitted attributes in <code>ProjectsController</code></p>
  <pre><code>def project_params
  params.require(:project).permit(:title, :description, :status)
end</code></pre>
</blockquote>

<h2>Explanation</h2>
<blockquote>
  <h3>Enum</h3>
  <p>
    Declare an enum attribute where the values map to integers in the database, but can be queried by name.
  </p>
  <p>
    Additionally, <code>enum</code> will create the <code>bang!</code> and <code>boolean?</code> versions for each possible value.
  </p>
  <p>
    Read more on <a href="http://api.rubyonrails.org/v4.1.0/classes/ActiveRecord/Enum.html">ActiveRecord Enum</a>.
  </p>
</blockquote>

app/views/steps/authentication_with_devise.html.erb
<h1 class="page-header">Adding Authentication with Devise</h1>
<blockquote>
  <p>Devise is a flexible authentication solution for Rails based on Warden.</p>
  <p>Warden is a Rack-based middleware, designed to provide a mechanism for authentication in Ruby web applications.  It is a common mechanism that fits into the Rack Machinery to offer powerful options for authentication.</p>
  <p>Devise is a complete MVC solution based on Rails engines and a modularity concept: use just what you really need.</p>
</blockquote>

<h2>Goals</h2>
<blockquote>
  <p>
    We will install an authentication system to prevent hackers, thieves, robots and other undesirable guests from accessing our data.
  </p>
  <ul>
    <li><h4>Add Devise to your dependency list</h4></li>
    <li><h4>Ask bundle to update your dependencies</h4></li>
  </ul>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>To add <code>Devise</code> to your application, simply tell <code>Bundler</code> to load it from <a href="http://rubygems.org/gems">rubygems.org</a></p>
  <p>Start by adding the following line to your <code>Gemfile</code></p>
  <pre><code class='ruby'>gem 'devise'</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Run <code>bundle</code> from the terminal to add <code>Devise</code> to your application</p>
  <pre><code class='ruby'>bundle</code></pre>
  <p>
    <a href="http://bundler.io/">Bundler</a> provides a consistent environment for Ruby projects by tracking and installing the exact gems and versions that are needed.
  </p>
  <p>Bundler is an exit from dependency hell, and ensures that the gems you need are present in development, staging, and production.</p>
  <div class="alert alert-info">Find yourself squinting over the result? Try <code>bundle | grep devise</code></div>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>
    Use the <code>Devise</code> generator to generator an <code>initializer</code>. Read more on <a href="http://guides.rubyonrails.org/initialization.html">Rails Initialization Process</a>
  </p>
  <pre><code class="ruby">rails g devise:install</code></pre>
</blockquote>

<h2>Explanation</h2>
<blockquote>
  <p>
    From <a href="http://guides.rubyonrails.org/engines.html">Getting Started with Engines</a> Rails Guide:
  </p>
  <p>
    Engines can be considered miniature applications that provide functionality to
    their host applications. A Rails application is actually just a "supercharged"
    engine, with the <code>Rails::Application</code> class inheriting a lot of its behavior
    from <code>Rails::Engine</code>.
  </p>
  <p>
    Have a look at <a href="https://github.com/plataformatec/devise">Devise</a> and observe the folder architecture.
  </p>
  <p>Now is also a good time to have a look at <a href="https://www.ruby-toolbox.com/">Ruby Toolbox</a>. Ruby Toolbox is a giant categorized collection of available gems with some meta data associated to it. You can easily find the gem you're looking for and see if it is still under development.</p>
</blockquote>

app/views/steps/create_comments.html.erb
<h1 class="page-header">Create Comments</h1>
<blockquote>
  <table class="table table-bordered">
    <thead><tr><th>Comments</th></tr></thead>
    <tbody>
      <tr><td>id</td></tr>
      <tr><td>text</td></tr>
      <tr><td>created_by_id</td></tr>
      <tr><td>commentable_id</td></tr>
      <tr><td>commentable_type</td></tr>
    </tbody>
  </table>
  <p>
    We need a way for users to keep track of various activity on the project without polluting the project's description.
  </p>
  <p>
    So we decide to add comments to our application.
  </p>
  <p>
    Knowing how versatile comments can be, we assume we will need commenting in other parts of our application other than projects. To do so, we keep polymorphism in mind.
  </p>
</blockquote>
<h2>Goals</h2>
<ul>
  <li><h4>Create a <code>Comment</code> model and database structure</h4></li>
  <li><h4>Learn about Rails Polymorphism</h4></li>
  <li><h4>Add comments/projects relationship</h4></li>
  <li><h4>Add comments/users relationship</h4></li>
</ul>

<h3>Step 1</h3>
<blockquote>
  <p>Use Rails model generator to quickly create a Comment model with the desired information.</p>
  <pre><code>rails g model comment text:text user:references commentable:references{polymorphic}</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Migrate your database to create a `comments` table</p>
  <pre><code>rake db:migrate</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Associate Projects to Comments by adding this line to <code>app/models/project.rb</code></p>
  <pre><code>has_many :comments, as: :commentable</code></pre>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p>Associate Users to Comments by adding this line to <code>app/models/user.rb</code></p>
  <pre><code>has_many :comments</code></pre>
</blockquote>

<h3>Step 5</h3>
<blockquote>
  <p>Ensure our associations are working properly by testing with the Rails console</p>
  <pre><code>$ rails c
project = Project.first
project.comments
project.comments.create(text: "What's up doc?", user: User.first)
user = User.first
user.comments</code></pre>
</blockquote>

<h2>Explanation</h2>
<blockquote>
  <p>With polymorphic associations, a model can belong to more than one other model, on a single association.</p>
  <p>We declared the <code>commentable</code> interface to share the comments association to other models.</p>
  <p>Read more about polymorphic associations in <a href="http://guides.rubyonrails.org/association_basics.html#polymorphic-associations">ActiveRecord Associations</a> Rails Guide</p>
</blockquote>

app/views/steps/creating_projects.html.erb
<h1 class="page-header">Creating Projects</h1>
<h2>Goals</h2>
<blockquote>
  <p>The project management system has a list of projects that people can work on. We'll store our projects in the database.</p>
  <table class="table table-bordered">
    <thead><tr><th>Projects</th></tr></thead>
    <tbody>
      <tr><td>id</td></tr>
      <tr><td>title</td></tr>
      <tr><td>description</td></tr>
    </tbody>
  </table>
  <p>In this step you'll do the following:</p>
  <ul>
    <li>
      <div class="message">
        <p>Create a a simple <em>Table</em> in the database for projects with a title and a description</p>
      </div>
    </li>
    <li>
      <div class="message">
        <p>Automatically generate the corresponding <em>Scaffold</em> in Rails (namely, the <em>Model</em>, the <em>View</em>, and the <em>Controller</em>).</p>
      </div>
    </li>
  </ul>
</blockquote>
<h3>Step 1</h3>
<blockquote>
  <div class="console">
    <span>Type this in the terminal:</span>
    <pre><code>rails generate scaffold project title:string description:text</code></pre>
  </div>
  <div class="message">
    <ul>
      <li>
        <code>generate scaffold</code> tells rails to create everything necessary to get up and running with projects.
      </li>
      <li>
        <code>project</code> tells rails the name of the new model.
      </li>
      <li>
        <code>title:string</code> says that projects have a title, which is a "string".
      </li>
      <li>
        <code>description:text</code> says that projects have a description which is a "text".
      </li>
    </ul>
  </div>
</blockquote>
<h3>Step 2</h3>
<blockquote>
  <div class="console">
    <span>Type this in the terminal:</span><code>rake db:migrate</code>
  </div>
  <div class="message">
    <p>This tells rails to update the database to include a table for our new model.</p>
  </div>
</blockquote>
<h3>Step 3</h3>
<blockquote>
  <p>Set your home route to list projects by adding this line to <code>config/routes.rb</code></p>
  <pre><code>root 'projects#index'</code></pre>
</blockquote>
<h2>Explanation</h2>
<blockquote>
  <h4>Rake</h4>
  <div class="message">
    <p><code>rake</code> <em>(ruby make)</em> is a tool that allows you to run small Ruby programs (<strong>tasks</strong>) that you use often in your application.</p>

    <p>Here, <code>rake db:migrate</code> is a task provided by the Rails framework. It creates a bunch of new files, including a <em>migration</em>, a <em>model</em>, a <em>view</em>, and a <em>controller</em>.</p>
  </div>
  <div class="alert alert-info">
    <h5>
      <i class="fa fa-info-circle fa-2x"></i>
      You can run <code>rake -T</code> to see a list of all the <code>rake</code> commands your app currently responds to, along with a short description of each task.
    </h5>
  </div>
</blockquote>

app/views/steps/display_comments.html.erb
<h1 class="page-header">Display Comments</h1>
<blockquote>
  <p>
    We have created a <code>Comment</code> model and database table to store our projects' comments. Let's list the comments for each projects and add a counter to our index view for visibility.
  </p>
</blockquote>
<h2>Goals</h2>
<blockquote>
  <ul>
    <li><h4>Order comments starting with the most recent on top</h4></li>
    <li><h4>Render a collection of comments with a single partial</h4></li>
    <li><h4>Add comments count to projects index</h4></li>
  </ul>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>Start by instantiating a <code>@comments</code> variable to hold our projects' comments. In our <code>ProjectsController</code>, let's define <code>@comments</code> ordered with the most recent on top.</p>
  <pre><code class="ruby">class ProjectsController &lt; ApplicationController
  # ...
  def show
    @comments = @project.comments.order(created_at: :desc)
  end
  # ...
end</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Use <code>render</code> to display a collection of comments. Rails determines the name of the partial to use by looking at the model name in the collection. In this case, Rails will look for a partial at <code>app/views/comments/_comment.html.erb</code>.</p>
  <p>Add the <code>render</code> block in <code>projects/show.html.erb</code> to the bottom of the file.</p>
  <pre><code>&lt;h3&gt;Comments&lt;/h3&gt;
&lt;%= render @comments %&gt;
</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Next, create a partial <code>comments/_comment.html.erb</code> and add the following code:</p>
  <pre><code>&lt;div class="comment"&gt;
  &lt;blockquote&gt;
    &lt;p&gt;&lt;%= comment.text %&gt;&lt;/p&gt;
    &lt;p&gt;
      Written by &lt;cite&gt;&lt;%= comment.user.try(:email) %&gt;&lt;/cite&gt; &lt;%= time_ago_in_words(comment.created_at) %&gt; ago
    &lt;/p&gt;
  &lt;/blockquote&gt;
  &lt;hr&gt;
&lt;/div&gt;</code></pre>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p>Finally, we will add a comments count to our index to increase visibility. Would you know how to do this one alone?</p>
</blockquote>

<h2>Explanation</h2>
<blockquote>
  <p>
    <code>render</code> is not specific to your controller and can also be useful in your views. It can be use in many different ways. Read <a href="http://guides.rubyonrails.org/layouts_and_rendering.html#using-render">Layouts and Rendering</a> Rails guide to learn more.
  </p>
</blockquote>

app/views/steps/getting_started.html.erb
<h1 class="page-header">Getting Started</h1>
<%= image_tag 'Start_page.png', alt: '' %>
<h2>Goals</h2>
<ul>
  <li>
    <div class="message">
      <p>Create Your New Application</p>
    </div>
  </li>
  <div class="message">
    <p>Let's get started! By the end of this step, we'll have a brand-spankin'-new (empty) rails app.</p>
  </div>
</ul>

<h2>Steps</h2>
<div class="alert alert-info">
  <p>
    <i class="fa fa-info-circle fa-2x"></i>
    Don't hesitate to ask questions if you have <em>any</em> problems!
  </p>
</div>
<h3>Step 1</h3>
<blockquote>
  <div class="console">
    <span>Type this in the terminal where you want to create your new rails application:</span>
    <pre><code>rails new milo -m https://gist.githubusercontent.com/mathieugagne/11214649/raw/c22dfbe6bc628fc9222a91ac1ca68180fb3f368e/suggestotron.rb</code></pre>
  </div>
  <div class="message">
    <p><code>rails new</code> creates a new rails project with the name you give.</p>
  </div>
  <div class="message">
    <p>In this case we told it to create a new project called <code>milo</code>. We'll go into detail on what it created shortly.</p>
  </div>
</blockquote>
<div class="step">
  <h3>Step 2</h3>
  <blockquote>
    <div class="console">
      <span>Type this in the terminal:</span><code>cd milo</code>
    </div>
    <div class="message">
      <p>'cd' stands for change directory.</p>
    </div>
    <div class="message">
      <p>'cd milo' makes milo our current directory.</p>
    </div>
  </blockquote>
</div>
<div class="step">
  <h3>Step 3</h3>
  <blockquote>
    <div class="message">
      <p>Open the milo folder as a project in your text editor.</p>

      <p>In <strong>Sublime Text 2</strong>, you can use the <code>Project &gt; Add Folder to Project...</code> menu option:</p>

      <p><%= image_tag "sublime_add_folder_to_project.png", alt: '' %></p>
    </div>
  </blockquote>
</div>

app/views/steps/next_steps.html.erb
<h1 class="page-header">Next Steps</h1>
<blockquote>
  <p>It is now in your hands to make Milo better.</p>
  <p>Here are some of the things you can do to improve Milo (and practice your Rails skills):</p>
  <ul>
    <li><h4>Sort projects using table headers</h4></li>
    <li><h4>Add counter cache for projects comments</h4></li>
    <li><h4>Add tags and categories to filter your projects</h4></li>
  </ul>
</blockquote>

<h3>Thank you!</h3>

<h2>Explore</h2>
<blockquote>
  <p>
    <a href="http://api.rubyonrails.org/v4.1.0/">rubyonrails.org</a> has extensive documentation on everything touching Rails. It provides links to the source code, explanations, configurations, examples and much more. Have a look at <a href="http://api.rubyonrails.org/v4.1.0/">http://api.rubyonrails.org/v4.1.0/</a>
  </p>
</blockquote>

<h3>Next lesson: Front End Development</h3>
<blockquote>
  <p>
    In next lesson, we will give Milo a beauty treatment.
  </p>
  <ul>
    <li>Learn the basic Rails view helpers</li>
    <li>Use CSS to adjust the layout and style of Milo</li>
    <li>Add a navigation bar to the top with essential links</li>
    <li>Use javascript to display flash messages that disappear after 5 seconds</li>
    <li>Add a weather widget to our sidebar (optional)</li>
  </ul>
</blockquote>